# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reportpreview.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportPreview(object):
    def setupUi(self, ReportPreview):
        ReportPreview.setObjectName(_fromUtf8("ReportPreview"))
        ReportPreview.resize(800, 1200)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(49, 55, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 55, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 55, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 55, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 55, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 55, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        ReportPreview.setPalette(palette)
        self.PageLayout = QtGui.QVBoxLayout(ReportPreview)
        self.PageLayout.setMargin(4)
        self.PageLayout.setSpacing(0)
        self.PageLayout.setObjectName(_fromUtf8("PageLayout"))
        self.HeaderLayout = QtGui.QHBoxLayout()
        self.HeaderLayout.setMargin(0)
        self.HeaderLayout.setSpacing(0)
        self.HeaderLayout.setObjectName(_fromUtf8("HeaderLayout"))
        self.ProjectInfoLayout = QtGui.QVBoxLayout()
        self.ProjectInfoLayout.setMargin(8)
        self.ProjectInfoLayout.setSpacing(4)
        self.ProjectInfoLayout.setObjectName(_fromUtf8("ProjectInfoLayout"))
        self.label = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.ProjectInfoLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ProjectInfoLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.ProjectInfoLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ProjectInfoLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ProjectInfoLayout.addWidget(self.label_5)
        self.HeaderLayout.addLayout(self.ProjectInfoLayout)
        self.line_2 = QtGui.QFrame(ReportPreview)
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.HeaderLayout.addWidget(self.line_2)
        self.BigImageWidget = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BigImageWidget.sizePolicy().hasHeightForWidth())
        self.BigImageWidget.setSizePolicy(sizePolicy)
        self.BigImageWidget.setObjectName(_fromUtf8("BigImageWidget"))
        self.HeaderLayout.addWidget(self.BigImageWidget)
        self.PageLayout.addLayout(self.HeaderLayout)
        self.PiecesLayout = QtGui.QVBoxLayout()
        self.PiecesLayout.setMargin(0)
        self.PiecesLayout.setSpacing(0)
        self.PiecesLayout.setObjectName(_fromUtf8("PiecesLayout"))
        self.line = QtGui.QFrame(ReportPreview)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.PiecesLayout.addWidget(self.line)
        self.PiecesRowLayout = QtGui.QHBoxLayout()
        self.PiecesRowLayout.setMargin(0)
        self.PiecesRowLayout.setSpacing(0)
        self.PiecesRowLayout.setObjectName(_fromUtf8("PiecesRowLayout"))
        self.ImageLayout = QtGui.QVBoxLayout()
        self.ImageLayout.setMargin(0)
        self.ImageLayout.setSpacing(0)
        self.ImageLayout.setObjectName(_fromUtf8("ImageLayout"))
        self.ImageHeaderLayout = QtGui.QHBoxLayout()
        self.ImageHeaderLayout.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout.setSpacing(0)
        self.ImageHeaderLayout.setObjectName(_fromUtf8("ImageHeaderLayout"))
        self.label_8 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ImageHeaderLayout.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.ImageHeaderLayout.addWidget(self.label_9)
        self.label_7 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ImageHeaderLayout.addWidget(self.label_7)
        self.ImageLayout.addLayout(self.ImageHeaderLayout)
        self.widget_6 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.label_10 = QtGui.QLabel(self.widget_6)
        self.label_10.setGeometry(QtCore.QRect(140, 100, 71, 20))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ImageLayout.addWidget(self.widget_6)
        self.label_6 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.ImageLayout.addWidget(self.label_6)
        self.PiecesRowLayout.addLayout(self.ImageLayout)
        self.line_21 = QtGui.QFrame(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_21.sizePolicy().hasHeightForWidth())
        self.line_21.setSizePolicy(sizePolicy)
        self.line_21.setFrameShadow(QtGui.QFrame.Plain)
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.PiecesRowLayout.addWidget(self.line_21)
        self.ImageLayout1 = QtGui.QVBoxLayout()
        self.ImageLayout1.setMargin(0)
        self.ImageLayout1.setSpacing(0)
        self.ImageLayout1.setObjectName(_fromUtf8("ImageLayout1"))
        self.ImageHeaderLayout_2 = QtGui.QHBoxLayout()
        self.ImageHeaderLayout_2.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout_2.setSpacing(0)
        self.ImageHeaderLayout_2.setObjectName(_fromUtf8("ImageHeaderLayout_2"))
        self.label_81 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_81.sizePolicy().hasHeightForWidth())
        self.label_81.setSizePolicy(sizePolicy)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.ImageHeaderLayout_2.addWidget(self.label_81)
        self.label_91 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_91.sizePolicy().hasHeightForWidth())
        self.label_91.setSizePolicy(sizePolicy)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.ImageHeaderLayout_2.addWidget(self.label_91)
        self.label_71 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_71.sizePolicy().hasHeightForWidth())
        self.label_71.setSizePolicy(sizePolicy)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.ImageHeaderLayout_2.addWidget(self.label_71)
        self.ImageLayout1.addLayout(self.ImageHeaderLayout_2)
        self.widget_61 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_61.sizePolicy().hasHeightForWidth())
        self.widget_61.setSizePolicy(sizePolicy)
        self.widget_61.setObjectName(_fromUtf8("widget_61"))
        self.ImageLayout1.addWidget(self.widget_61)
        self.label_61 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.ImageLayout1.addWidget(self.label_61)
        self.PiecesRowLayout.addLayout(self.ImageLayout1)
        self.line_22 = QtGui.QFrame(ReportPreview)
        self.line_22.setFrameShadow(QtGui.QFrame.Plain)
        self.line_22.setFrameShape(QtGui.QFrame.VLine)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.PiecesRowLayout.addWidget(self.line_22)
        self.ImageLayout2 = QtGui.QVBoxLayout()
        self.ImageLayout2.setMargin(0)
        self.ImageLayout2.setSpacing(0)
        self.ImageLayout2.setObjectName(_fromUtf8("ImageLayout2"))
        self.ImageHeaderLayout_3 = QtGui.QHBoxLayout()
        self.ImageHeaderLayout_3.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout_3.setSpacing(0)
        self.ImageHeaderLayout_3.setObjectName(_fromUtf8("ImageHeaderLayout_3"))
        self.label_82 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_82.sizePolicy().hasHeightForWidth())
        self.label_82.setSizePolicy(sizePolicy)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.ImageHeaderLayout_3.addWidget(self.label_82)
        self.label_92 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.ImageHeaderLayout_3.addWidget(self.label_92)
        self.label_72 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.ImageHeaderLayout_3.addWidget(self.label_72)
        self.ImageLayout2.addLayout(self.ImageHeaderLayout_3)
        self.widget_62 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_62.sizePolicy().hasHeightForWidth())
        self.widget_62.setSizePolicy(sizePolicy)
        self.widget_62.setObjectName(_fromUtf8("widget_62"))
        self.ImageLayout2.addWidget(self.widget_62)
        self.label_62 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.ImageLayout2.addWidget(self.label_62)
        self.PiecesRowLayout.addLayout(self.ImageLayout2)
        self.PiecesLayout.addLayout(self.PiecesRowLayout)
        self.line1 = QtGui.QFrame(ReportPreview)
        self.line1.setFrameShadow(QtGui.QFrame.Plain)
        self.line1.setFrameShape(QtGui.QFrame.HLine)
        self.line1.setObjectName(_fromUtf8("line1"))
        self.PiecesLayout.addWidget(self.line1)
        self.PiecesRowLayout1 = QtGui.QHBoxLayout()
        self.PiecesRowLayout1.setMargin(0)
        self.PiecesRowLayout1.setSpacing(0)
        self.PiecesRowLayout1.setObjectName(_fromUtf8("PiecesRowLayout1"))
        self.ImageLayout3 = QtGui.QVBoxLayout()
        self.ImageLayout3.setMargin(0)
        self.ImageLayout3.setSpacing(0)
        self.ImageLayout3.setObjectName(_fromUtf8("ImageLayout3"))
        self.ImageHeaderLayout1 = QtGui.QHBoxLayout()
        self.ImageHeaderLayout1.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout1.setSpacing(0)
        self.ImageHeaderLayout1.setObjectName(_fromUtf8("ImageHeaderLayout1"))
        self.label_83 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.ImageHeaderLayout1.addWidget(self.label_83)
        self.label_93 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.ImageHeaderLayout1.addWidget(self.label_93)
        self.label_73 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.ImageHeaderLayout1.addWidget(self.label_73)
        self.ImageLayout3.addLayout(self.ImageHeaderLayout1)
        self.widget_63 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_63.sizePolicy().hasHeightForWidth())
        self.widget_63.setSizePolicy(sizePolicy)
        self.widget_63.setObjectName(_fromUtf8("widget_63"))
        self.ImageLayout3.addWidget(self.widget_63)
        self.label_63 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.ImageLayout3.addWidget(self.label_63)
        self.PiecesRowLayout1.addLayout(self.ImageLayout3)
        self.line_23 = QtGui.QFrame(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_23.sizePolicy().hasHeightForWidth())
        self.line_23.setSizePolicy(sizePolicy)
        self.line_23.setFrameShadow(QtGui.QFrame.Plain)
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.PiecesRowLayout1.addWidget(self.line_23)
        self.ImageLayout4 = QtGui.QVBoxLayout()
        self.ImageLayout4.setMargin(0)
        self.ImageLayout4.setSpacing(0)
        self.ImageLayout4.setObjectName(_fromUtf8("ImageLayout4"))
        self.ImageHeaderLayout_21 = QtGui.QHBoxLayout()
        self.ImageHeaderLayout_21.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout_21.setSpacing(0)
        self.ImageHeaderLayout_21.setObjectName(_fromUtf8("ImageHeaderLayout_21"))
        self.label_84 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_84.sizePolicy().hasHeightForWidth())
        self.label_84.setSizePolicy(sizePolicy)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.ImageHeaderLayout_21.addWidget(self.label_84)
        self.label_94 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_94.sizePolicy().hasHeightForWidth())
        self.label_94.setSizePolicy(sizePolicy)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.ImageHeaderLayout_21.addWidget(self.label_94)
        self.label_74 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.ImageHeaderLayout_21.addWidget(self.label_74)
        self.ImageLayout4.addLayout(self.ImageHeaderLayout_21)
        self.widget_64 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_64.sizePolicy().hasHeightForWidth())
        self.widget_64.setSizePolicy(sizePolicy)
        self.widget_64.setObjectName(_fromUtf8("widget_64"))
        self.ImageLayout4.addWidget(self.widget_64)
        self.label_64 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.ImageLayout4.addWidget(self.label_64)
        self.PiecesRowLayout1.addLayout(self.ImageLayout4)
        self.line_24 = QtGui.QFrame(ReportPreview)
        self.line_24.setFrameShadow(QtGui.QFrame.Plain)
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.PiecesRowLayout1.addWidget(self.line_24)
        self.ImageLayout5 = QtGui.QVBoxLayout()
        self.ImageLayout5.setMargin(0)
        self.ImageLayout5.setSpacing(0)
        self.ImageLayout5.setObjectName(_fromUtf8("ImageLayout5"))
        self.ImageHeaderLayout_31 = QtGui.QHBoxLayout()
        self.ImageHeaderLayout_31.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout_31.setSpacing(0)
        self.ImageHeaderLayout_31.setObjectName(_fromUtf8("ImageHeaderLayout_31"))
        self.label_85 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_85.sizePolicy().hasHeightForWidth())
        self.label_85.setSizePolicy(sizePolicy)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.ImageHeaderLayout_31.addWidget(self.label_85)
        self.label_95 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_95.sizePolicy().hasHeightForWidth())
        self.label_95.setSizePolicy(sizePolicy)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.ImageHeaderLayout_31.addWidget(self.label_95)
        self.label_75 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.ImageHeaderLayout_31.addWidget(self.label_75)
        self.ImageLayout5.addLayout(self.ImageHeaderLayout_31)
        self.widget_65 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_65.sizePolicy().hasHeightForWidth())
        self.widget_65.setSizePolicy(sizePolicy)
        self.widget_65.setObjectName(_fromUtf8("widget_65"))
        self.ImageLayout5.addWidget(self.widget_65)
        self.label_65 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.ImageLayout5.addWidget(self.label_65)
        self.PiecesRowLayout1.addLayout(self.ImageLayout5)
        self.PiecesLayout.addLayout(self.PiecesRowLayout1)
        self.line2 = QtGui.QFrame(ReportPreview)
        self.line2.setFrameShadow(QtGui.QFrame.Plain)
        self.line2.setFrameShape(QtGui.QFrame.HLine)
        self.line2.setObjectName(_fromUtf8("line2"))
        self.PiecesLayout.addWidget(self.line2)
        self.PiecesRowLayout2 = QtGui.QHBoxLayout()
        self.PiecesRowLayout2.setMargin(0)
        self.PiecesRowLayout2.setSpacing(0)
        self.PiecesRowLayout2.setObjectName(_fromUtf8("PiecesRowLayout2"))
        self.ImageLayout6 = QtGui.QVBoxLayout()
        self.ImageLayout6.setMargin(0)
        self.ImageLayout6.setSpacing(0)
        self.ImageLayout6.setObjectName(_fromUtf8("ImageLayout6"))
        self.ImageHeaderLayout2 = QtGui.QHBoxLayout()
        self.ImageHeaderLayout2.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout2.setSpacing(0)
        self.ImageHeaderLayout2.setObjectName(_fromUtf8("ImageHeaderLayout2"))
        self.label_86 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.ImageHeaderLayout2.addWidget(self.label_86)
        self.label_96 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_96.sizePolicy().hasHeightForWidth())
        self.label_96.setSizePolicy(sizePolicy)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.ImageHeaderLayout2.addWidget(self.label_96)
        self.label_76 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.ImageHeaderLayout2.addWidget(self.label_76)
        self.ImageLayout6.addLayout(self.ImageHeaderLayout2)
        self.widget_66 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_66.sizePolicy().hasHeightForWidth())
        self.widget_66.setSizePolicy(sizePolicy)
        self.widget_66.setObjectName(_fromUtf8("widget_66"))
        self.ImageLayout6.addWidget(self.widget_66)
        self.label_66 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.ImageLayout6.addWidget(self.label_66)
        self.PiecesRowLayout2.addLayout(self.ImageLayout6)
        self.line_25 = QtGui.QFrame(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_25.sizePolicy().hasHeightForWidth())
        self.line_25.setSizePolicy(sizePolicy)
        self.line_25.setFrameShadow(QtGui.QFrame.Plain)
        self.line_25.setFrameShape(QtGui.QFrame.VLine)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.PiecesRowLayout2.addWidget(self.line_25)
        self.ImageLayout7 = QtGui.QVBoxLayout()
        self.ImageLayout7.setMargin(0)
        self.ImageLayout7.setSpacing(0)
        self.ImageLayout7.setObjectName(_fromUtf8("ImageLayout7"))
        self.ImageHeaderLayout_22 = QtGui.QHBoxLayout()
        self.ImageHeaderLayout_22.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout_22.setSpacing(0)
        self.ImageHeaderLayout_22.setObjectName(_fromUtf8("ImageHeaderLayout_22"))
        self.label_87 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_87.sizePolicy().hasHeightForWidth())
        self.label_87.setSizePolicy(sizePolicy)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.ImageHeaderLayout_22.addWidget(self.label_87)
        self.label_97 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_97.sizePolicy().hasHeightForWidth())
        self.label_97.setSizePolicy(sizePolicy)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.ImageHeaderLayout_22.addWidget(self.label_97)
        self.label_77 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.ImageHeaderLayout_22.addWidget(self.label_77)
        self.ImageLayout7.addLayout(self.ImageHeaderLayout_22)
        self.widget_67 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_67.sizePolicy().hasHeightForWidth())
        self.widget_67.setSizePolicy(sizePolicy)
        self.widget_67.setObjectName(_fromUtf8("widget_67"))
        self.ImageLayout7.addWidget(self.widget_67)
        self.label_67 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.ImageLayout7.addWidget(self.label_67)
        self.PiecesRowLayout2.addLayout(self.ImageLayout7)
        self.line_26 = QtGui.QFrame(ReportPreview)
        self.line_26.setFrameShadow(QtGui.QFrame.Plain)
        self.line_26.setFrameShape(QtGui.QFrame.VLine)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.PiecesRowLayout2.addWidget(self.line_26)
        self.ImageLayout8 = QtGui.QVBoxLayout()
        self.ImageLayout8.setMargin(0)
        self.ImageLayout8.setSpacing(0)
        self.ImageLayout8.setObjectName(_fromUtf8("ImageLayout8"))
        self.ImageHeaderLayout_32 = QtGui.QHBoxLayout()
        self.ImageHeaderLayout_32.setContentsMargins(4, 0, 0, 0)
        self.ImageHeaderLayout_32.setSpacing(0)
        self.ImageHeaderLayout_32.setObjectName(_fromUtf8("ImageHeaderLayout_32"))
        self.label_88 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_88.sizePolicy().hasHeightForWidth())
        self.label_88.setSizePolicy(sizePolicy)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.ImageHeaderLayout_32.addWidget(self.label_88)
        self.label_98 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_98.sizePolicy().hasHeightForWidth())
        self.label_98.setSizePolicy(sizePolicy)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.ImageHeaderLayout_32.addWidget(self.label_98)
        self.label_78 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.ImageHeaderLayout_32.addWidget(self.label_78)
        self.ImageLayout8.addLayout(self.ImageHeaderLayout_32)
        self.widget_68 = QtGui.QWidget(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_68.sizePolicy().hasHeightForWidth())
        self.widget_68.setSizePolicy(sizePolicy)
        self.widget_68.setObjectName(_fromUtf8("widget_68"))
        self.ImageLayout8.addWidget(self.widget_68)
        self.label_68 = QtGui.QLabel(ReportPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.ImageLayout8.addWidget(self.label_68)
        self.PiecesRowLayout2.addLayout(self.ImageLayout8)
        self.PiecesLayout.addLayout(self.PiecesRowLayout2)
        self.line3 = QtGui.QFrame(ReportPreview)
        self.line3.setFrameShadow(QtGui.QFrame.Plain)
        self.line3.setFrameShape(QtGui.QFrame.HLine)
        self.line3.setObjectName(_fromUtf8("line3"))
        self.PiecesLayout.addWidget(self.line3)
        self.PageLayout.addLayout(self.PiecesLayout)

        self.retranslateUi(ReportPreview)
        QtCore.QMetaObject.connectSlotsByName(ReportPreview)

    def retranslateUi(self, ReportPreview):
        ReportPreview.setWindowTitle(_translate("ReportPreview", "ReportPreview", None))
        self.label.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_2.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_3.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_4.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_5.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_8.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_9.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_7.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_6.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_81.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_91.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_71.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_61.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_82.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_92.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_72.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_62.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_83.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_93.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_73.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_63.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_84.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_94.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_74.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_64.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_85.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_95.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_75.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_65.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_86.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_96.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_76.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_66.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_87.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_97.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_77.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_67.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_88.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_98.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_78.setText(_translate("ReportPreview", "TextLabel", None))
        self.label_68.setText(_translate("ReportPreview", "TextLabel", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ReportPreview = QtGui.QWidget()
    ui = Ui_ReportPreview()
    ui.setupUi(ReportPreview)
    ReportPreview.show()
    sys.exit(app.exec_())

